# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage:
    jobs:
      - job: 'test'
        steps:
          - script: cd Project0/TestStoreDb && dotnet test
            displayName: 'test'
      - job: 'publish'
        dependsOn: 'test'
        steps:
          - script: cd Project0/TestStoreDb && dotnet publish
            displayName: 'publish'