# wipe the database and migrations, then rebuild from scratch
rebuild-db:
    rm -Rf StoreCli/store.sqlite
    rm -Rf StoreDb/Migrations
    dotnet ef migrations add --startup-project StoreCli --project StoreDb InitialCreate
    dotnet ef database update --startup-project StoreCli --project StoreDb

# build all
build:
    dotnet build StoreDb
    dotnet build StoreCli

# build cli
build-cli:
    dotnet build StoreCli

# build database project
build-db:
    dotnet build StoreDb

# run cli project
run:
    dotnet run StoreCli

# run tests
test:
    dotnet test TestStoreDb
