# re-migrate the database
re-migrate:
    rm -Rf StoreCli/store.sqlite
    dotnet ef database update --startup-project StoreCli --project StoreDb

# build all
build:
    cd StoreDb && dotnet build
    cd StoreCli && dotnet build

# build cli
build-cli:
    cd StoreCli && dotnet build

# build database project
build-db:
    cd StoreDb && dotnet build

# run cli project
run:
    cd StoreCli && dotnet run

# run tests
test:
    dotnet test TestStoreDb

demo-remove-db:
    mv StoreCli/store.sqlite StoreCli/store.sqlite.bak
    
demo-restore-db:
    mv StoreCli/store.sqlite.bak StoreCli/store.sqlite